LoginPage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup')
]

login/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username

login/views.py
import re

from django.shortcuts import render

from .models import User


def index(request):
    if is_logged(request):
        context = {'username': logged_user(request)}
        return render(request, 'login/index.html', context)
    else:
        return login(request)


def login(request):
    if not is_logged(request):
        if request.POST:
            if is_login_valid(request):
                login_session_set(request)
                return render(request, 'login/success.html', {'msg': 'You have successfully signed in.'})
            else:
                return render(request, 'login/login.html', {'wrong_login': True})
        else:
            return render(request, 'login/login.html')
    else:
        return index(request)


def signup(request):
    if not is_logged(request):
        if request.POST:
            reg_username = request.POST['username']
            reg_password = request.POST['password']

            if not is_username_valid(reg_username):
                return render(request, 'login/signup.html', {'err_msg': 'Username is not valid.'})
            elif not is_password_valid(reg_password):
                return render(request, 'login/signup.html', {'err_msg': 'Password is not valid.'})
            elif is_registered(reg_username):
                return render(request, 'login/signup.html', {'err_msg': "This username is already used."})
            else:
                register_account(reg_username, reg_password)
                return render(request, 'login/success.html', {'msg': 'You have successfully signed up.'
                                                                         'Now you can login.'})
        else:
            return render(request, 'login/signup.html')
    else:
        return render(request, 'login/index.html')


def logout(request):
    login_session_delete(request)
    return login(request)


def is_logged(request):
    user = request.session.get('username')
    if user is None:
        return False
    else:
        return True


def logged_user(request):
    return request.session.get('username')


def is_login_valid(request):
    username_req = request.POST['username']
    password_req = request.POST['password']

    try:
        User.objects.get(
            username=username_req,
            password=password_req,
        )
    except (KeyError, User.DoesNotExist):
        return False

    return True


def login_session_set(request):
    request.session['username'] = request.POST['username']


def login_session_delete(request):
    del(request.session['username'])


def is_username_valid(reg_username):
    if re.search('^(?=.{4,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$', reg_username):
        return True
    return False


def is_password_valid(reg_password):
    if re.search('^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{4,}$', reg_password):
        return True
    return False


def is_registered(reg_username):
    try:
        User.objects.get(
            username=reg_username
        )
    except (KeyError, User.DoesNotExist):
        return False

    return True


def register_account(reg_username, reg_password):
    account = User(username=reg_username, password=reg_password)
    account.save()

login/templates/login/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

    {% if already_registered == True %}
    <h2>Sorry, this username is already used.</h2>
    {% endif %}

    <form action="{% url 'login:register' %}" method="post">
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" id="username" name="username" maxlength="50">

        <label for="password">Password</label>
        <input type="password", id="password", name="password", maxlength="50">

        <input type="submit" value="Sign Up">
    </form>

</body>
</html>

templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wellcome</title>
</head>
<body>

    <h2>Wellcome back, {{ username }}</h2>

    </br>

    <button><a href="{% url 'login:logout' %}">Logout</a></button>

</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
</head>
<body>

    {% if wrong_login == True %}
    <h2>Wrong username or password. Please try again.</h2>
    {% endif %}

    <form action="{% url 'login:login' %}" method="post">
        {% csrf_token %}

        <label for="username">Username: </label>
        <input type="text" name="username" maxlength="50" id="username">
        <label for="password">Password: </label>
        <input type="password", name="password" maxlength="50" id="password">

        <input type="submit" value="Login">
    </form>

</body>
</html>

templates/login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

    {% if err_msg %}
    <h2>{{ err_msg }}</h2>
    {% endif %}

    <form action="{% url 'login:signup' %}" method="post">
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" id="username" name="username" maxlength="50">

        <label for="password">Password</label>
        <input type="password", id="password", name="password", maxlength="50">

        <input type="submit" value="Sign Up">
    </form>

</body>
</html>

templates/login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>

    <h2>Success!</h2>
    <h2>{{ msg }}</h2>

    <a href="/..">Main page</a>

</body>
</html>